// Code generated by ent, DO NOT EDIT.

package teamadconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the teamadconfig type in the database.
	Label = "team_ad_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTeamID holds the string denoting the team_id field in the database.
	FieldTeamID = "team_id"
	// FieldDirectoryID holds the string denoting the directory_id field in the database.
	FieldDirectoryID = "directory_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldBaseDn holds the string denoting the base_dn field in the database.
	FieldBaseDn = "base_dn"
	// FieldBindDn holds the string denoting the bind_dn field in the database.
	FieldBindDn = "bind_dn"
	// FieldBindPasswordCiphertext holds the string denoting the bind_password_ciphertext field in the database.
	FieldBindPasswordCiphertext = "bind_password_ciphertext"
	// FieldCaPem holds the string denoting the ca_pem field in the database.
	FieldCaPem = "ca_pem"
	// FieldAllowedGroupDNS holds the string denoting the allowed_group_dns field in the database.
	FieldAllowedGroupDNS = "allowed_group_dns"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTeam holds the string denoting the team edge name in mutations.
	EdgeTeam = "team"
	// Table holds the table name of the teamadconfig in the database.
	Table = "team_ad_configs"
	// TeamTable is the table that holds the team relation/edge.
	TeamTable = "team_ad_configs"
	// TeamInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	TeamInverseTable = "teams"
	// TeamColumn is the table column denoting the team relation/edge.
	TeamColumn = "team_id"
)

// Columns holds all SQL columns for teamadconfig fields.
var Columns = []string{
	FieldID,
	FieldTeamID,
	FieldDirectoryID,
	FieldEnabled,
	FieldDisplayName,
	FieldURL,
	FieldBaseDn,
	FieldBindDn,
	FieldBindPasswordCiphertext,
	FieldCaPem,
	FieldAllowedGroupDNS,
	FieldRevision,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultDisplayName holds the default value on creation for the "display_name" field.
	DefaultDisplayName string
	// DefaultAllowedGroupDNS holds the default value on creation for the "allowed_group_dns" field.
	DefaultAllowedGroupDNS []string
	// DefaultRevision holds the default value on creation for the "revision" field.
	DefaultRevision int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the TeamADConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTeamID orders the results by the team_id field.
func ByTeamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamID, opts...).ToFunc()
}

// ByDirectoryID orders the results by the directory_id field.
func ByDirectoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirectoryID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByBaseDn orders the results by the base_dn field.
func ByBaseDn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseDn, opts...).ToFunc()
}

// ByBindDn orders the results by the bind_dn field.
func ByBindDn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBindDn, opts...).ToFunc()
}

// ByBindPasswordCiphertext orders the results by the bind_password_ciphertext field.
func ByBindPasswordCiphertext(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBindPasswordCiphertext, opts...).ToFunc()
}

// ByCaPem orders the results by the ca_pem field.
func ByCaPem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaPem, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTeamField orders the results by team field.
func ByTeamField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamStep(), sql.OrderByField(field, opts...))
	}
}
func newTeamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, TeamTable, TeamColumn),
	)
}
