// Code generated by ent, DO NOT EDIT.

package teamadconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/63747756/jingjiaagent/backend/db/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLTE(FieldID, id))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldTeamID, v))
}

// DirectoryID applies equality check predicate on the "directory_id" field. It's identical to DirectoryIDEQ.
func DirectoryID(v uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldDirectoryID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldEnabled, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldDisplayName, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldURL, v))
}

// BaseDn applies equality check predicate on the "base_dn" field. It's identical to BaseDnEQ.
func BaseDn(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldBaseDn, v))
}

// BindDn applies equality check predicate on the "bind_dn" field. It's identical to BindDnEQ.
func BindDn(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldBindDn, v))
}

// BindPasswordCiphertext applies equality check predicate on the "bind_password_ciphertext" field. It's identical to BindPasswordCiphertextEQ.
func BindPasswordCiphertext(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldBindPasswordCiphertext, v))
}

// CaPem applies equality check predicate on the "ca_pem" field. It's identical to CaPemEQ.
func CaPem(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldCaPem, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldRevision, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotIn(FieldTeamID, vs...))
}

// DirectoryIDEQ applies the EQ predicate on the "directory_id" field.
func DirectoryIDEQ(v uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldDirectoryID, v))
}

// DirectoryIDNEQ applies the NEQ predicate on the "directory_id" field.
func DirectoryIDNEQ(v uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNEQ(FieldDirectoryID, v))
}

// DirectoryIDIn applies the In predicate on the "directory_id" field.
func DirectoryIDIn(vs ...uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIn(FieldDirectoryID, vs...))
}

// DirectoryIDNotIn applies the NotIn predicate on the "directory_id" field.
func DirectoryIDNotIn(vs ...uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotIn(FieldDirectoryID, vs...))
}

// DirectoryIDGT applies the GT predicate on the "directory_id" field.
func DirectoryIDGT(v uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGT(FieldDirectoryID, v))
}

// DirectoryIDGTE applies the GTE predicate on the "directory_id" field.
func DirectoryIDGTE(v uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGTE(FieldDirectoryID, v))
}

// DirectoryIDLT applies the LT predicate on the "directory_id" field.
func DirectoryIDLT(v uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLT(FieldDirectoryID, v))
}

// DirectoryIDLTE applies the LTE predicate on the "directory_id" field.
func DirectoryIDLTE(v uuid.UUID) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLTE(FieldDirectoryID, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNEQ(FieldEnabled, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldContainsFold(FieldDisplayName, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldContainsFold(FieldURL, v))
}

// BaseDnEQ applies the EQ predicate on the "base_dn" field.
func BaseDnEQ(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldBaseDn, v))
}

// BaseDnNEQ applies the NEQ predicate on the "base_dn" field.
func BaseDnNEQ(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNEQ(FieldBaseDn, v))
}

// BaseDnIn applies the In predicate on the "base_dn" field.
func BaseDnIn(vs ...string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIn(FieldBaseDn, vs...))
}

// BaseDnNotIn applies the NotIn predicate on the "base_dn" field.
func BaseDnNotIn(vs ...string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotIn(FieldBaseDn, vs...))
}

// BaseDnGT applies the GT predicate on the "base_dn" field.
func BaseDnGT(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGT(FieldBaseDn, v))
}

// BaseDnGTE applies the GTE predicate on the "base_dn" field.
func BaseDnGTE(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGTE(FieldBaseDn, v))
}

// BaseDnLT applies the LT predicate on the "base_dn" field.
func BaseDnLT(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLT(FieldBaseDn, v))
}

// BaseDnLTE applies the LTE predicate on the "base_dn" field.
func BaseDnLTE(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLTE(FieldBaseDn, v))
}

// BaseDnContains applies the Contains predicate on the "base_dn" field.
func BaseDnContains(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldContains(FieldBaseDn, v))
}

// BaseDnHasPrefix applies the HasPrefix predicate on the "base_dn" field.
func BaseDnHasPrefix(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldHasPrefix(FieldBaseDn, v))
}

// BaseDnHasSuffix applies the HasSuffix predicate on the "base_dn" field.
func BaseDnHasSuffix(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldHasSuffix(FieldBaseDn, v))
}

// BaseDnIsNil applies the IsNil predicate on the "base_dn" field.
func BaseDnIsNil() predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIsNull(FieldBaseDn))
}

// BaseDnNotNil applies the NotNil predicate on the "base_dn" field.
func BaseDnNotNil() predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotNull(FieldBaseDn))
}

// BaseDnEqualFold applies the EqualFold predicate on the "base_dn" field.
func BaseDnEqualFold(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEqualFold(FieldBaseDn, v))
}

// BaseDnContainsFold applies the ContainsFold predicate on the "base_dn" field.
func BaseDnContainsFold(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldContainsFold(FieldBaseDn, v))
}

// BindDnEQ applies the EQ predicate on the "bind_dn" field.
func BindDnEQ(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldBindDn, v))
}

// BindDnNEQ applies the NEQ predicate on the "bind_dn" field.
func BindDnNEQ(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNEQ(FieldBindDn, v))
}

// BindDnIn applies the In predicate on the "bind_dn" field.
func BindDnIn(vs ...string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIn(FieldBindDn, vs...))
}

// BindDnNotIn applies the NotIn predicate on the "bind_dn" field.
func BindDnNotIn(vs ...string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotIn(FieldBindDn, vs...))
}

// BindDnGT applies the GT predicate on the "bind_dn" field.
func BindDnGT(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGT(FieldBindDn, v))
}

// BindDnGTE applies the GTE predicate on the "bind_dn" field.
func BindDnGTE(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGTE(FieldBindDn, v))
}

// BindDnLT applies the LT predicate on the "bind_dn" field.
func BindDnLT(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLT(FieldBindDn, v))
}

// BindDnLTE applies the LTE predicate on the "bind_dn" field.
func BindDnLTE(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLTE(FieldBindDn, v))
}

// BindDnContains applies the Contains predicate on the "bind_dn" field.
func BindDnContains(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldContains(FieldBindDn, v))
}

// BindDnHasPrefix applies the HasPrefix predicate on the "bind_dn" field.
func BindDnHasPrefix(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldHasPrefix(FieldBindDn, v))
}

// BindDnHasSuffix applies the HasSuffix predicate on the "bind_dn" field.
func BindDnHasSuffix(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldHasSuffix(FieldBindDn, v))
}

// BindDnIsNil applies the IsNil predicate on the "bind_dn" field.
func BindDnIsNil() predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIsNull(FieldBindDn))
}

// BindDnNotNil applies the NotNil predicate on the "bind_dn" field.
func BindDnNotNil() predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotNull(FieldBindDn))
}

// BindDnEqualFold applies the EqualFold predicate on the "bind_dn" field.
func BindDnEqualFold(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEqualFold(FieldBindDn, v))
}

// BindDnContainsFold applies the ContainsFold predicate on the "bind_dn" field.
func BindDnContainsFold(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldContainsFold(FieldBindDn, v))
}

// BindPasswordCiphertextEQ applies the EQ predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextEQ(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldBindPasswordCiphertext, v))
}

// BindPasswordCiphertextNEQ applies the NEQ predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextNEQ(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNEQ(FieldBindPasswordCiphertext, v))
}

// BindPasswordCiphertextIn applies the In predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextIn(vs ...string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIn(FieldBindPasswordCiphertext, vs...))
}

// BindPasswordCiphertextNotIn applies the NotIn predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextNotIn(vs ...string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotIn(FieldBindPasswordCiphertext, vs...))
}

// BindPasswordCiphertextGT applies the GT predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextGT(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGT(FieldBindPasswordCiphertext, v))
}

// BindPasswordCiphertextGTE applies the GTE predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextGTE(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGTE(FieldBindPasswordCiphertext, v))
}

// BindPasswordCiphertextLT applies the LT predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextLT(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLT(FieldBindPasswordCiphertext, v))
}

// BindPasswordCiphertextLTE applies the LTE predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextLTE(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLTE(FieldBindPasswordCiphertext, v))
}

// BindPasswordCiphertextContains applies the Contains predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextContains(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldContains(FieldBindPasswordCiphertext, v))
}

// BindPasswordCiphertextHasPrefix applies the HasPrefix predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextHasPrefix(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldHasPrefix(FieldBindPasswordCiphertext, v))
}

// BindPasswordCiphertextHasSuffix applies the HasSuffix predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextHasSuffix(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldHasSuffix(FieldBindPasswordCiphertext, v))
}

// BindPasswordCiphertextIsNil applies the IsNil predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextIsNil() predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIsNull(FieldBindPasswordCiphertext))
}

// BindPasswordCiphertextNotNil applies the NotNil predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextNotNil() predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotNull(FieldBindPasswordCiphertext))
}

// BindPasswordCiphertextEqualFold applies the EqualFold predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextEqualFold(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEqualFold(FieldBindPasswordCiphertext, v))
}

// BindPasswordCiphertextContainsFold applies the ContainsFold predicate on the "bind_password_ciphertext" field.
func BindPasswordCiphertextContainsFold(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldContainsFold(FieldBindPasswordCiphertext, v))
}

// CaPemEQ applies the EQ predicate on the "ca_pem" field.
func CaPemEQ(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldCaPem, v))
}

// CaPemNEQ applies the NEQ predicate on the "ca_pem" field.
func CaPemNEQ(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNEQ(FieldCaPem, v))
}

// CaPemIn applies the In predicate on the "ca_pem" field.
func CaPemIn(vs ...string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIn(FieldCaPem, vs...))
}

// CaPemNotIn applies the NotIn predicate on the "ca_pem" field.
func CaPemNotIn(vs ...string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotIn(FieldCaPem, vs...))
}

// CaPemGT applies the GT predicate on the "ca_pem" field.
func CaPemGT(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGT(FieldCaPem, v))
}

// CaPemGTE applies the GTE predicate on the "ca_pem" field.
func CaPemGTE(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGTE(FieldCaPem, v))
}

// CaPemLT applies the LT predicate on the "ca_pem" field.
func CaPemLT(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLT(FieldCaPem, v))
}

// CaPemLTE applies the LTE predicate on the "ca_pem" field.
func CaPemLTE(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLTE(FieldCaPem, v))
}

// CaPemContains applies the Contains predicate on the "ca_pem" field.
func CaPemContains(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldContains(FieldCaPem, v))
}

// CaPemHasPrefix applies the HasPrefix predicate on the "ca_pem" field.
func CaPemHasPrefix(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldHasPrefix(FieldCaPem, v))
}

// CaPemHasSuffix applies the HasSuffix predicate on the "ca_pem" field.
func CaPemHasSuffix(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldHasSuffix(FieldCaPem, v))
}

// CaPemIsNil applies the IsNil predicate on the "ca_pem" field.
func CaPemIsNil() predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIsNull(FieldCaPem))
}

// CaPemNotNil applies the NotNil predicate on the "ca_pem" field.
func CaPemNotNil() predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotNull(FieldCaPem))
}

// CaPemEqualFold applies the EqualFold predicate on the "ca_pem" field.
func CaPemEqualFold(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEqualFold(FieldCaPem, v))
}

// CaPemContainsFold applies the ContainsFold predicate on the "ca_pem" field.
func CaPemContainsFold(v string) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldContainsFold(FieldCaPem, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLTE(FieldRevision, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.TeamADConfig {
	return predicate.TeamADConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.TeamADConfig {
	return predicate.TeamADConfig(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamADConfig) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamADConfig) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamADConfig) predicate.TeamADConfig {
	return predicate.TeamADConfig(sql.NotPredicates(p))
}
