// Code generated by ent, DO NOT EDIT.

package teamgroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/63747756/jingjiaagent/backend/db/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLTE(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldDeletedAt, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldTeamID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldName, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldSource, v))
}

// DirectoryID applies equality check predicate on the "directory_id" field. It's identical to DirectoryIDEQ.
func DirectoryID(v uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldDirectoryID, v))
}

// ExternalID applies equality check predicate on the "external_id" field. It's identical to ExternalIDEQ.
func ExternalID(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldExternalID, v))
}

// ExternalDn applies equality check predicate on the "external_dn" field. It's identical to ExternalDnEQ.
func ExternalDn(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldExternalDn, v))
}

// OuPath applies equality check predicate on the "ou_path" field. It's identical to OuPathEQ.
func OuPath(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldOuPath, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldLastSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotNull(FieldDeletedAt))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotIn(FieldTeamID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldContainsFold(FieldName, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldContainsFold(FieldSource, v))
}

// DirectoryIDEQ applies the EQ predicate on the "directory_id" field.
func DirectoryIDEQ(v uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldDirectoryID, v))
}

// DirectoryIDNEQ applies the NEQ predicate on the "directory_id" field.
func DirectoryIDNEQ(v uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNEQ(FieldDirectoryID, v))
}

// DirectoryIDIn applies the In predicate on the "directory_id" field.
func DirectoryIDIn(vs ...uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIn(FieldDirectoryID, vs...))
}

// DirectoryIDNotIn applies the NotIn predicate on the "directory_id" field.
func DirectoryIDNotIn(vs ...uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotIn(FieldDirectoryID, vs...))
}

// DirectoryIDGT applies the GT predicate on the "directory_id" field.
func DirectoryIDGT(v uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGT(FieldDirectoryID, v))
}

// DirectoryIDGTE applies the GTE predicate on the "directory_id" field.
func DirectoryIDGTE(v uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGTE(FieldDirectoryID, v))
}

// DirectoryIDLT applies the LT predicate on the "directory_id" field.
func DirectoryIDLT(v uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLT(FieldDirectoryID, v))
}

// DirectoryIDLTE applies the LTE predicate on the "directory_id" field.
func DirectoryIDLTE(v uuid.UUID) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLTE(FieldDirectoryID, v))
}

// DirectoryIDIsNil applies the IsNil predicate on the "directory_id" field.
func DirectoryIDIsNil() predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIsNull(FieldDirectoryID))
}

// DirectoryIDNotNil applies the NotNil predicate on the "directory_id" field.
func DirectoryIDNotNil() predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotNull(FieldDirectoryID))
}

// ExternalIDEQ applies the EQ predicate on the "external_id" field.
func ExternalIDEQ(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldExternalID, v))
}

// ExternalIDNEQ applies the NEQ predicate on the "external_id" field.
func ExternalIDNEQ(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNEQ(FieldExternalID, v))
}

// ExternalIDIn applies the In predicate on the "external_id" field.
func ExternalIDIn(vs ...string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIn(FieldExternalID, vs...))
}

// ExternalIDNotIn applies the NotIn predicate on the "external_id" field.
func ExternalIDNotIn(vs ...string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotIn(FieldExternalID, vs...))
}

// ExternalIDGT applies the GT predicate on the "external_id" field.
func ExternalIDGT(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGT(FieldExternalID, v))
}

// ExternalIDGTE applies the GTE predicate on the "external_id" field.
func ExternalIDGTE(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGTE(FieldExternalID, v))
}

// ExternalIDLT applies the LT predicate on the "external_id" field.
func ExternalIDLT(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLT(FieldExternalID, v))
}

// ExternalIDLTE applies the LTE predicate on the "external_id" field.
func ExternalIDLTE(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLTE(FieldExternalID, v))
}

// ExternalIDContains applies the Contains predicate on the "external_id" field.
func ExternalIDContains(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldContains(FieldExternalID, v))
}

// ExternalIDHasPrefix applies the HasPrefix predicate on the "external_id" field.
func ExternalIDHasPrefix(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldHasPrefix(FieldExternalID, v))
}

// ExternalIDHasSuffix applies the HasSuffix predicate on the "external_id" field.
func ExternalIDHasSuffix(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldHasSuffix(FieldExternalID, v))
}

// ExternalIDIsNil applies the IsNil predicate on the "external_id" field.
func ExternalIDIsNil() predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIsNull(FieldExternalID))
}

// ExternalIDNotNil applies the NotNil predicate on the "external_id" field.
func ExternalIDNotNil() predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotNull(FieldExternalID))
}

// ExternalIDEqualFold applies the EqualFold predicate on the "external_id" field.
func ExternalIDEqualFold(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEqualFold(FieldExternalID, v))
}

// ExternalIDContainsFold applies the ContainsFold predicate on the "external_id" field.
func ExternalIDContainsFold(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldContainsFold(FieldExternalID, v))
}

// ExternalDnEQ applies the EQ predicate on the "external_dn" field.
func ExternalDnEQ(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldExternalDn, v))
}

// ExternalDnNEQ applies the NEQ predicate on the "external_dn" field.
func ExternalDnNEQ(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNEQ(FieldExternalDn, v))
}

// ExternalDnIn applies the In predicate on the "external_dn" field.
func ExternalDnIn(vs ...string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIn(FieldExternalDn, vs...))
}

// ExternalDnNotIn applies the NotIn predicate on the "external_dn" field.
func ExternalDnNotIn(vs ...string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotIn(FieldExternalDn, vs...))
}

// ExternalDnGT applies the GT predicate on the "external_dn" field.
func ExternalDnGT(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGT(FieldExternalDn, v))
}

// ExternalDnGTE applies the GTE predicate on the "external_dn" field.
func ExternalDnGTE(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGTE(FieldExternalDn, v))
}

// ExternalDnLT applies the LT predicate on the "external_dn" field.
func ExternalDnLT(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLT(FieldExternalDn, v))
}

// ExternalDnLTE applies the LTE predicate on the "external_dn" field.
func ExternalDnLTE(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLTE(FieldExternalDn, v))
}

// ExternalDnContains applies the Contains predicate on the "external_dn" field.
func ExternalDnContains(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldContains(FieldExternalDn, v))
}

// ExternalDnHasPrefix applies the HasPrefix predicate on the "external_dn" field.
func ExternalDnHasPrefix(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldHasPrefix(FieldExternalDn, v))
}

// ExternalDnHasSuffix applies the HasSuffix predicate on the "external_dn" field.
func ExternalDnHasSuffix(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldHasSuffix(FieldExternalDn, v))
}

// ExternalDnIsNil applies the IsNil predicate on the "external_dn" field.
func ExternalDnIsNil() predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIsNull(FieldExternalDn))
}

// ExternalDnNotNil applies the NotNil predicate on the "external_dn" field.
func ExternalDnNotNil() predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotNull(FieldExternalDn))
}

// ExternalDnEqualFold applies the EqualFold predicate on the "external_dn" field.
func ExternalDnEqualFold(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEqualFold(FieldExternalDn, v))
}

// ExternalDnContainsFold applies the ContainsFold predicate on the "external_dn" field.
func ExternalDnContainsFold(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldContainsFold(FieldExternalDn, v))
}

// OuPathEQ applies the EQ predicate on the "ou_path" field.
func OuPathEQ(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldOuPath, v))
}

// OuPathNEQ applies the NEQ predicate on the "ou_path" field.
func OuPathNEQ(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNEQ(FieldOuPath, v))
}

// OuPathIn applies the In predicate on the "ou_path" field.
func OuPathIn(vs ...string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIn(FieldOuPath, vs...))
}

// OuPathNotIn applies the NotIn predicate on the "ou_path" field.
func OuPathNotIn(vs ...string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotIn(FieldOuPath, vs...))
}

// OuPathGT applies the GT predicate on the "ou_path" field.
func OuPathGT(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGT(FieldOuPath, v))
}

// OuPathGTE applies the GTE predicate on the "ou_path" field.
func OuPathGTE(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGTE(FieldOuPath, v))
}

// OuPathLT applies the LT predicate on the "ou_path" field.
func OuPathLT(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLT(FieldOuPath, v))
}

// OuPathLTE applies the LTE predicate on the "ou_path" field.
func OuPathLTE(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLTE(FieldOuPath, v))
}

// OuPathContains applies the Contains predicate on the "ou_path" field.
func OuPathContains(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldContains(FieldOuPath, v))
}

// OuPathHasPrefix applies the HasPrefix predicate on the "ou_path" field.
func OuPathHasPrefix(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldHasPrefix(FieldOuPath, v))
}

// OuPathHasSuffix applies the HasSuffix predicate on the "ou_path" field.
func OuPathHasSuffix(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldHasSuffix(FieldOuPath, v))
}

// OuPathIsNil applies the IsNil predicate on the "ou_path" field.
func OuPathIsNil() predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIsNull(FieldOuPath))
}

// OuPathNotNil applies the NotNil predicate on the "ou_path" field.
func OuPathNotNil() predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotNull(FieldOuPath))
}

// OuPathEqualFold applies the EqualFold predicate on the "ou_path" field.
func OuPathEqualFold(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEqualFold(FieldOuPath, v))
}

// OuPathContainsFold applies the ContainsFold predicate on the "ou_path" field.
func OuPathContainsFold(v string) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldContainsFold(FieldOuPath, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotNull(FieldLastSyncedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TeamGroup {
	return predicate.TeamGroup(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, MembersTable, MembersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.User) predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasModels applies the HasEdge predicate on the "models" edge.
func HasModels() predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ModelsTable, ModelsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasModelsWith applies the HasEdge predicate on the "models" edge with a given conditions (other predicates).
func HasModelsWith(preds ...predicate.Model) predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := newModelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasImages applies the HasEdge predicate on the "images" edge.
func HasImages() predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ImagesTable, ImagesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasImagesWith applies the HasEdge predicate on the "images" edge with a given conditions (other predicates).
func HasImagesWith(preds ...predicate.Image) predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := newImagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHosts applies the HasEdge predicate on the "hosts" edge.
func HasHosts() predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, HostsTable, HostsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHostsWith applies the HasEdge predicate on the "hosts" edge with a given conditions (other predicates).
func HasHostsWith(preds ...predicate.Host) predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := newHostsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMcpUpstreams applies the HasEdge predicate on the "mcp_upstreams" edge.
func HasMcpUpstreams() predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, McpUpstreamsTable, McpUpstreamsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMcpUpstreamsWith applies the HasEdge predicate on the "mcp_upstreams" edge with a given conditions (other predicates).
func HasMcpUpstreamsWith(preds ...predicate.MCPUpstream) predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := newMcpUpstreamsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeamGroupMembers applies the HasEdge predicate on the "team_group_members" edge.
func HasTeamGroupMembers() predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TeamGroupMembersTable, TeamGroupMembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamGroupMembersWith applies the HasEdge predicate on the "team_group_members" edge with a given conditions (other predicates).
func HasTeamGroupMembersWith(preds ...predicate.TeamGroupMember) predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := newTeamGroupMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeamGroupModels applies the HasEdge predicate on the "team_group_models" edge.
func HasTeamGroupModels() predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TeamGroupModelsTable, TeamGroupModelsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamGroupModelsWith applies the HasEdge predicate on the "team_group_models" edge with a given conditions (other predicates).
func HasTeamGroupModelsWith(preds ...predicate.TeamGroupModel) predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := newTeamGroupModelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeamGroupImages applies the HasEdge predicate on the "team_group_images" edge.
func HasTeamGroupImages() predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TeamGroupImagesTable, TeamGroupImagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamGroupImagesWith applies the HasEdge predicate on the "team_group_images" edge with a given conditions (other predicates).
func HasTeamGroupImagesWith(preds ...predicate.TeamGroupImage) predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := newTeamGroupImagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeamGroupHosts applies the HasEdge predicate on the "team_group_hosts" edge.
func HasTeamGroupHosts() predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TeamGroupHostsTable, TeamGroupHostsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamGroupHostsWith applies the HasEdge predicate on the "team_group_hosts" edge with a given conditions (other predicates).
func HasTeamGroupHostsWith(preds ...predicate.TeamGroupHost) predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := newTeamGroupHostsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeamGroupMcpUpstreams applies the HasEdge predicate on the "team_group_mcp_upstreams" edge.
func HasTeamGroupMcpUpstreams() predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TeamGroupMcpUpstreamsTable, TeamGroupMcpUpstreamsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamGroupMcpUpstreamsWith applies the HasEdge predicate on the "team_group_mcp_upstreams" edge with a given conditions (other predicates).
func HasTeamGroupMcpUpstreamsWith(preds ...predicate.TeamGroupMCPUpstream) predicate.TeamGroup {
	return predicate.TeamGroup(func(s *sql.Selector) {
		step := newTeamGroupMcpUpstreamsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamGroup) predicate.TeamGroup {
	return predicate.TeamGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamGroup) predicate.TeamGroup {
	return predicate.TeamGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamGroup) predicate.TeamGroup {
	return predicate.TeamGroup(sql.NotPredicates(p))
}
