// Code generated by ent, DO NOT EDIT.

package db

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/63747756/jingjiaagent/backend/db/team"
	"github.com/63747756/jingjiaagent/backend/db/teamadconfig"
	"github.com/google/uuid"
)

// TeamADConfig is the model entity for the TeamADConfig schema.
type TeamADConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID uuid.UUID `json:"team_id,omitempty"`
	// DirectoryID holds the value of the "directory_id" field.
	DirectoryID uuid.UUID `json:"directory_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// BaseDn holds the value of the "base_dn" field.
	BaseDn string `json:"base_dn,omitempty"`
	// BindDn holds the value of the "bind_dn" field.
	BindDn string `json:"bind_dn,omitempty"`
	// BindPasswordCiphertext holds the value of the "bind_password_ciphertext" field.
	BindPasswordCiphertext string `json:"bind_password_ciphertext,omitempty"`
	// CaPem holds the value of the "ca_pem" field.
	CaPem string `json:"ca_pem,omitempty"`
	// AllowedGroupDNS holds the value of the "allowed_group_dns" field.
	AllowedGroupDNS []string `json:"allowed_group_dns,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision int `json:"revision,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeamADConfigQuery when eager-loading is set.
	Edges        TeamADConfigEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeamADConfigEdges holds the relations/edges for other nodes in the graph.
type TeamADConfigEdges struct {
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamADConfigEdges) TeamOrErr() (*Team, error) {
	if e.Team != nil {
		return e.Team, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "team"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamADConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teamadconfig.FieldAllowedGroupDNS:
			values[i] = new([]byte)
		case teamadconfig.FieldEnabled:
			values[i] = new(sql.NullBool)
		case teamadconfig.FieldRevision:
			values[i] = new(sql.NullInt64)
		case teamadconfig.FieldDisplayName, teamadconfig.FieldURL, teamadconfig.FieldBaseDn, teamadconfig.FieldBindDn, teamadconfig.FieldBindPasswordCiphertext, teamadconfig.FieldCaPem:
			values[i] = new(sql.NullString)
		case teamadconfig.FieldCreatedAt, teamadconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case teamadconfig.FieldID, teamadconfig.FieldTeamID, teamadconfig.FieldDirectoryID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamADConfig fields.
func (_m *TeamADConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teamadconfig.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case teamadconfig.FieldTeamID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value != nil {
				_m.TeamID = *value
			}
		case teamadconfig.FieldDirectoryID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field directory_id", values[i])
			} else if value != nil {
				_m.DirectoryID = *value
			}
		case teamadconfig.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case teamadconfig.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case teamadconfig.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case teamadconfig.FieldBaseDn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_dn", values[i])
			} else if value.Valid {
				_m.BaseDn = value.String
			}
		case teamadconfig.FieldBindDn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bind_dn", values[i])
			} else if value.Valid {
				_m.BindDn = value.String
			}
		case teamadconfig.FieldBindPasswordCiphertext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bind_password_ciphertext", values[i])
			} else if value.Valid {
				_m.BindPasswordCiphertext = value.String
			}
		case teamadconfig.FieldCaPem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ca_pem", values[i])
			} else if value.Valid {
				_m.CaPem = value.String
			}
		case teamadconfig.FieldAllowedGroupDNS:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_group_dns", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedGroupDNS); err != nil {
					return fmt.Errorf("unmarshal field allowed_group_dns: %w", err)
				}
			}
		case teamadconfig.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = int(value.Int64)
			}
		case teamadconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case teamadconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamADConfig.
// This includes values selected through modifiers, order, etc.
func (_m *TeamADConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTeam queries the "team" edge of the TeamADConfig entity.
func (_m *TeamADConfig) QueryTeam() *TeamQuery {
	return NewTeamADConfigClient(_m.config).QueryTeam(_m)
}

// Update returns a builder for updating this TeamADConfig.
// Note that you need to call TeamADConfig.Unwrap() before calling this method if this TeamADConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TeamADConfig) Update() *TeamADConfigUpdateOne {
	return NewTeamADConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TeamADConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TeamADConfig) Unwrap() *TeamADConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: TeamADConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TeamADConfig) String() string {
	var builder strings.Builder
	builder.WriteString("TeamADConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("team_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamID))
	builder.WriteString(", ")
	builder.WriteString("directory_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DirectoryID))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("base_dn=")
	builder.WriteString(_m.BaseDn)
	builder.WriteString(", ")
	builder.WriteString("bind_dn=")
	builder.WriteString(_m.BindDn)
	builder.WriteString(", ")
	builder.WriteString("bind_password_ciphertext=")
	builder.WriteString(_m.BindPasswordCiphertext)
	builder.WriteString(", ")
	builder.WriteString("ca_pem=")
	builder.WriteString(_m.CaPem)
	builder.WriteString(", ")
	builder.WriteString("allowed_group_dns=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedGroupDNS))
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TeamADConfigs is a parsable slice of TeamADConfig.
type TeamADConfigs []*TeamADConfig
