// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/63747756/jingjiaagent/backend/db/predicate"
	"github.com/63747756/jingjiaagent/backend/db/team"
	"github.com/63747756/jingjiaagent/backend/db/teamadconfig"
	"github.com/google/uuid"
)

// TeamADConfigUpdate is the builder for updating TeamADConfig entities.
type TeamADConfigUpdate struct {
	config
	hooks     []Hook
	mutation  *TeamADConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TeamADConfigUpdate builder.
func (_u *TeamADConfigUpdate) Where(ps ...predicate.TeamADConfig) *TeamADConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamADConfigUpdate) SetTeamID(v uuid.UUID) *TeamADConfigUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamADConfigUpdate) SetNillableTeamID(v *uuid.UUID) *TeamADConfigUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetDirectoryID sets the "directory_id" field.
func (_u *TeamADConfigUpdate) SetDirectoryID(v uuid.UUID) *TeamADConfigUpdate {
	_u.mutation.SetDirectoryID(v)
	return _u
}

// SetNillableDirectoryID sets the "directory_id" field if the given value is not nil.
func (_u *TeamADConfigUpdate) SetNillableDirectoryID(v *uuid.UUID) *TeamADConfigUpdate {
	if v != nil {
		_u.SetDirectoryID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TeamADConfigUpdate) SetEnabled(v bool) *TeamADConfigUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TeamADConfigUpdate) SetNillableEnabled(v *bool) *TeamADConfigUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *TeamADConfigUpdate) SetDisplayName(v string) *TeamADConfigUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *TeamADConfigUpdate) SetNillableDisplayName(v *string) *TeamADConfigUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *TeamADConfigUpdate) SetURL(v string) *TeamADConfigUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *TeamADConfigUpdate) SetNillableURL(v *string) *TeamADConfigUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *TeamADConfigUpdate) ClearURL() *TeamADConfigUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetBaseDn sets the "base_dn" field.
func (_u *TeamADConfigUpdate) SetBaseDn(v string) *TeamADConfigUpdate {
	_u.mutation.SetBaseDn(v)
	return _u
}

// SetNillableBaseDn sets the "base_dn" field if the given value is not nil.
func (_u *TeamADConfigUpdate) SetNillableBaseDn(v *string) *TeamADConfigUpdate {
	if v != nil {
		_u.SetBaseDn(*v)
	}
	return _u
}

// ClearBaseDn clears the value of the "base_dn" field.
func (_u *TeamADConfigUpdate) ClearBaseDn() *TeamADConfigUpdate {
	_u.mutation.ClearBaseDn()
	return _u
}

// SetBindDn sets the "bind_dn" field.
func (_u *TeamADConfigUpdate) SetBindDn(v string) *TeamADConfigUpdate {
	_u.mutation.SetBindDn(v)
	return _u
}

// SetNillableBindDn sets the "bind_dn" field if the given value is not nil.
func (_u *TeamADConfigUpdate) SetNillableBindDn(v *string) *TeamADConfigUpdate {
	if v != nil {
		_u.SetBindDn(*v)
	}
	return _u
}

// ClearBindDn clears the value of the "bind_dn" field.
func (_u *TeamADConfigUpdate) ClearBindDn() *TeamADConfigUpdate {
	_u.mutation.ClearBindDn()
	return _u
}

// SetBindPasswordCiphertext sets the "bind_password_ciphertext" field.
func (_u *TeamADConfigUpdate) SetBindPasswordCiphertext(v string) *TeamADConfigUpdate {
	_u.mutation.SetBindPasswordCiphertext(v)
	return _u
}

// SetNillableBindPasswordCiphertext sets the "bind_password_ciphertext" field if the given value is not nil.
func (_u *TeamADConfigUpdate) SetNillableBindPasswordCiphertext(v *string) *TeamADConfigUpdate {
	if v != nil {
		_u.SetBindPasswordCiphertext(*v)
	}
	return _u
}

// ClearBindPasswordCiphertext clears the value of the "bind_password_ciphertext" field.
func (_u *TeamADConfigUpdate) ClearBindPasswordCiphertext() *TeamADConfigUpdate {
	_u.mutation.ClearBindPasswordCiphertext()
	return _u
}

// SetCaPem sets the "ca_pem" field.
func (_u *TeamADConfigUpdate) SetCaPem(v string) *TeamADConfigUpdate {
	_u.mutation.SetCaPem(v)
	return _u
}

// SetNillableCaPem sets the "ca_pem" field if the given value is not nil.
func (_u *TeamADConfigUpdate) SetNillableCaPem(v *string) *TeamADConfigUpdate {
	if v != nil {
		_u.SetCaPem(*v)
	}
	return _u
}

// ClearCaPem clears the value of the "ca_pem" field.
func (_u *TeamADConfigUpdate) ClearCaPem() *TeamADConfigUpdate {
	_u.mutation.ClearCaPem()
	return _u
}

// SetAllowedGroupDNS sets the "allowed_group_dns" field.
func (_u *TeamADConfigUpdate) SetAllowedGroupDNS(v []string) *TeamADConfigUpdate {
	_u.mutation.SetAllowedGroupDNS(v)
	return _u
}

// AppendAllowedGroupDNS appends value to the "allowed_group_dns" field.
func (_u *TeamADConfigUpdate) AppendAllowedGroupDNS(v []string) *TeamADConfigUpdate {
	_u.mutation.AppendAllowedGroupDNS(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *TeamADConfigUpdate) SetRevision(v int) *TeamADConfigUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *TeamADConfigUpdate) SetNillableRevision(v *int) *TeamADConfigUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *TeamADConfigUpdate) AddRevision(v int) *TeamADConfigUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TeamADConfigUpdate) SetCreatedAt(v time.Time) *TeamADConfigUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TeamADConfigUpdate) SetNillableCreatedAt(v *time.Time) *TeamADConfigUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamADConfigUpdate) SetUpdatedAt(v time.Time) *TeamADConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamADConfigUpdate) SetTeam(v *Team) *TeamADConfigUpdate {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamADConfigMutation object of the builder.
func (_u *TeamADConfigUpdate) Mutation() *TeamADConfigMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamADConfigUpdate) ClearTeam() *TeamADConfigUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamADConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamADConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamADConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamADConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamADConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teamadconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamADConfigUpdate) check() error {
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "TeamADConfig.team"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TeamADConfigUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TeamADConfigUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TeamADConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamadconfig.Table, teamadconfig.Columns, sqlgraph.NewFieldSpec(teamadconfig.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DirectoryID(); ok {
		_spec.SetField(teamadconfig.FieldDirectoryID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(teamadconfig.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(teamadconfig.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(teamadconfig.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(teamadconfig.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.BaseDn(); ok {
		_spec.SetField(teamadconfig.FieldBaseDn, field.TypeString, value)
	}
	if _u.mutation.BaseDnCleared() {
		_spec.ClearField(teamadconfig.FieldBaseDn, field.TypeString)
	}
	if value, ok := _u.mutation.BindDn(); ok {
		_spec.SetField(teamadconfig.FieldBindDn, field.TypeString, value)
	}
	if _u.mutation.BindDnCleared() {
		_spec.ClearField(teamadconfig.FieldBindDn, field.TypeString)
	}
	if value, ok := _u.mutation.BindPasswordCiphertext(); ok {
		_spec.SetField(teamadconfig.FieldBindPasswordCiphertext, field.TypeString, value)
	}
	if _u.mutation.BindPasswordCiphertextCleared() {
		_spec.ClearField(teamadconfig.FieldBindPasswordCiphertext, field.TypeString)
	}
	if value, ok := _u.mutation.CaPem(); ok {
		_spec.SetField(teamadconfig.FieldCaPem, field.TypeString, value)
	}
	if _u.mutation.CaPemCleared() {
		_spec.ClearField(teamadconfig.FieldCaPem, field.TypeString)
	}
	if value, ok := _u.mutation.AllowedGroupDNS(); ok {
		_spec.SetField(teamadconfig.FieldAllowedGroupDNS, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedGroupDNS(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, teamadconfig.FieldAllowedGroupDNS, value)
		})
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(teamadconfig.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(teamadconfig.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(teamadconfig.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teamadconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamadconfig.TeamTable,
			Columns: []string{teamadconfig.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamadconfig.TeamTable,
			Columns: []string{teamadconfig.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamadconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamADConfigUpdateOne is the builder for updating a single TeamADConfig entity.
type TeamADConfigUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TeamADConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTeamID sets the "team_id" field.
func (_u *TeamADConfigUpdateOne) SetTeamID(v uuid.UUID) *TeamADConfigUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamADConfigUpdateOne) SetNillableTeamID(v *uuid.UUID) *TeamADConfigUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetDirectoryID sets the "directory_id" field.
func (_u *TeamADConfigUpdateOne) SetDirectoryID(v uuid.UUID) *TeamADConfigUpdateOne {
	_u.mutation.SetDirectoryID(v)
	return _u
}

// SetNillableDirectoryID sets the "directory_id" field if the given value is not nil.
func (_u *TeamADConfigUpdateOne) SetNillableDirectoryID(v *uuid.UUID) *TeamADConfigUpdateOne {
	if v != nil {
		_u.SetDirectoryID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TeamADConfigUpdateOne) SetEnabled(v bool) *TeamADConfigUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TeamADConfigUpdateOne) SetNillableEnabled(v *bool) *TeamADConfigUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *TeamADConfigUpdateOne) SetDisplayName(v string) *TeamADConfigUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *TeamADConfigUpdateOne) SetNillableDisplayName(v *string) *TeamADConfigUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *TeamADConfigUpdateOne) SetURL(v string) *TeamADConfigUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *TeamADConfigUpdateOne) SetNillableURL(v *string) *TeamADConfigUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *TeamADConfigUpdateOne) ClearURL() *TeamADConfigUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetBaseDn sets the "base_dn" field.
func (_u *TeamADConfigUpdateOne) SetBaseDn(v string) *TeamADConfigUpdateOne {
	_u.mutation.SetBaseDn(v)
	return _u
}

// SetNillableBaseDn sets the "base_dn" field if the given value is not nil.
func (_u *TeamADConfigUpdateOne) SetNillableBaseDn(v *string) *TeamADConfigUpdateOne {
	if v != nil {
		_u.SetBaseDn(*v)
	}
	return _u
}

// ClearBaseDn clears the value of the "base_dn" field.
func (_u *TeamADConfigUpdateOne) ClearBaseDn() *TeamADConfigUpdateOne {
	_u.mutation.ClearBaseDn()
	return _u
}

// SetBindDn sets the "bind_dn" field.
func (_u *TeamADConfigUpdateOne) SetBindDn(v string) *TeamADConfigUpdateOne {
	_u.mutation.SetBindDn(v)
	return _u
}

// SetNillableBindDn sets the "bind_dn" field if the given value is not nil.
func (_u *TeamADConfigUpdateOne) SetNillableBindDn(v *string) *TeamADConfigUpdateOne {
	if v != nil {
		_u.SetBindDn(*v)
	}
	return _u
}

// ClearBindDn clears the value of the "bind_dn" field.
func (_u *TeamADConfigUpdateOne) ClearBindDn() *TeamADConfigUpdateOne {
	_u.mutation.ClearBindDn()
	return _u
}

// SetBindPasswordCiphertext sets the "bind_password_ciphertext" field.
func (_u *TeamADConfigUpdateOne) SetBindPasswordCiphertext(v string) *TeamADConfigUpdateOne {
	_u.mutation.SetBindPasswordCiphertext(v)
	return _u
}

// SetNillableBindPasswordCiphertext sets the "bind_password_ciphertext" field if the given value is not nil.
func (_u *TeamADConfigUpdateOne) SetNillableBindPasswordCiphertext(v *string) *TeamADConfigUpdateOne {
	if v != nil {
		_u.SetBindPasswordCiphertext(*v)
	}
	return _u
}

// ClearBindPasswordCiphertext clears the value of the "bind_password_ciphertext" field.
func (_u *TeamADConfigUpdateOne) ClearBindPasswordCiphertext() *TeamADConfigUpdateOne {
	_u.mutation.ClearBindPasswordCiphertext()
	return _u
}

// SetCaPem sets the "ca_pem" field.
func (_u *TeamADConfigUpdateOne) SetCaPem(v string) *TeamADConfigUpdateOne {
	_u.mutation.SetCaPem(v)
	return _u
}

// SetNillableCaPem sets the "ca_pem" field if the given value is not nil.
func (_u *TeamADConfigUpdateOne) SetNillableCaPem(v *string) *TeamADConfigUpdateOne {
	if v != nil {
		_u.SetCaPem(*v)
	}
	return _u
}

// ClearCaPem clears the value of the "ca_pem" field.
func (_u *TeamADConfigUpdateOne) ClearCaPem() *TeamADConfigUpdateOne {
	_u.mutation.ClearCaPem()
	return _u
}

// SetAllowedGroupDNS sets the "allowed_group_dns" field.
func (_u *TeamADConfigUpdateOne) SetAllowedGroupDNS(v []string) *TeamADConfigUpdateOne {
	_u.mutation.SetAllowedGroupDNS(v)
	return _u
}

// AppendAllowedGroupDNS appends value to the "allowed_group_dns" field.
func (_u *TeamADConfigUpdateOne) AppendAllowedGroupDNS(v []string) *TeamADConfigUpdateOne {
	_u.mutation.AppendAllowedGroupDNS(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *TeamADConfigUpdateOne) SetRevision(v int) *TeamADConfigUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *TeamADConfigUpdateOne) SetNillableRevision(v *int) *TeamADConfigUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *TeamADConfigUpdateOne) AddRevision(v int) *TeamADConfigUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TeamADConfigUpdateOne) SetCreatedAt(v time.Time) *TeamADConfigUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TeamADConfigUpdateOne) SetNillableCreatedAt(v *time.Time) *TeamADConfigUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamADConfigUpdateOne) SetUpdatedAt(v time.Time) *TeamADConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamADConfigUpdateOne) SetTeam(v *Team) *TeamADConfigUpdateOne {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamADConfigMutation object of the builder.
func (_u *TeamADConfigUpdateOne) Mutation() *TeamADConfigMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamADConfigUpdateOne) ClearTeam() *TeamADConfigUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// Where appends a list predicates to the TeamADConfigUpdate builder.
func (_u *TeamADConfigUpdateOne) Where(ps ...predicate.TeamADConfig) *TeamADConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamADConfigUpdateOne) Select(field string, fields ...string) *TeamADConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamADConfig entity.
func (_u *TeamADConfigUpdateOne) Save(ctx context.Context) (*TeamADConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamADConfigUpdateOne) SaveX(ctx context.Context) *TeamADConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamADConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamADConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamADConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teamadconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamADConfigUpdateOne) check() error {
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "TeamADConfig.team"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TeamADConfigUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TeamADConfigUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TeamADConfigUpdateOne) sqlSave(ctx context.Context) (_node *TeamADConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamadconfig.Table, teamadconfig.Columns, sqlgraph.NewFieldSpec(teamadconfig.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "TeamADConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamadconfig.FieldID)
		for _, f := range fields {
			if !teamadconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != teamadconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DirectoryID(); ok {
		_spec.SetField(teamadconfig.FieldDirectoryID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(teamadconfig.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(teamadconfig.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(teamadconfig.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(teamadconfig.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.BaseDn(); ok {
		_spec.SetField(teamadconfig.FieldBaseDn, field.TypeString, value)
	}
	if _u.mutation.BaseDnCleared() {
		_spec.ClearField(teamadconfig.FieldBaseDn, field.TypeString)
	}
	if value, ok := _u.mutation.BindDn(); ok {
		_spec.SetField(teamadconfig.FieldBindDn, field.TypeString, value)
	}
	if _u.mutation.BindDnCleared() {
		_spec.ClearField(teamadconfig.FieldBindDn, field.TypeString)
	}
	if value, ok := _u.mutation.BindPasswordCiphertext(); ok {
		_spec.SetField(teamadconfig.FieldBindPasswordCiphertext, field.TypeString, value)
	}
	if _u.mutation.BindPasswordCiphertextCleared() {
		_spec.ClearField(teamadconfig.FieldBindPasswordCiphertext, field.TypeString)
	}
	if value, ok := _u.mutation.CaPem(); ok {
		_spec.SetField(teamadconfig.FieldCaPem, field.TypeString, value)
	}
	if _u.mutation.CaPemCleared() {
		_spec.ClearField(teamadconfig.FieldCaPem, field.TypeString)
	}
	if value, ok := _u.mutation.AllowedGroupDNS(); ok {
		_spec.SetField(teamadconfig.FieldAllowedGroupDNS, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedGroupDNS(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, teamadconfig.FieldAllowedGroupDNS, value)
		})
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(teamadconfig.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(teamadconfig.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(teamadconfig.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teamadconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamadconfig.TeamTable,
			Columns: []string{teamadconfig.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamadconfig.TeamTable,
			Columns: []string{teamadconfig.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TeamADConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamadconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
