// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/63747756/jingjiaagent/backend/db/team"
	"github.com/63747756/jingjiaagent/backend/db/teamadconfig"
	"github.com/google/uuid"
)

// TeamADConfigCreate is the builder for creating a TeamADConfig entity.
type TeamADConfigCreate struct {
	config
	mutation *TeamADConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTeamID sets the "team_id" field.
func (_c *TeamADConfigCreate) SetTeamID(v uuid.UUID) *TeamADConfigCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetDirectoryID sets the "directory_id" field.
func (_c *TeamADConfigCreate) SetDirectoryID(v uuid.UUID) *TeamADConfigCreate {
	_c.mutation.SetDirectoryID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *TeamADConfigCreate) SetEnabled(v bool) *TeamADConfigCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *TeamADConfigCreate) SetNillableEnabled(v *bool) *TeamADConfigCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *TeamADConfigCreate) SetDisplayName(v string) *TeamADConfigCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *TeamADConfigCreate) SetNillableDisplayName(v *string) *TeamADConfigCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *TeamADConfigCreate) SetURL(v string) *TeamADConfigCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *TeamADConfigCreate) SetNillableURL(v *string) *TeamADConfigCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetBaseDn sets the "base_dn" field.
func (_c *TeamADConfigCreate) SetBaseDn(v string) *TeamADConfigCreate {
	_c.mutation.SetBaseDn(v)
	return _c
}

// SetNillableBaseDn sets the "base_dn" field if the given value is not nil.
func (_c *TeamADConfigCreate) SetNillableBaseDn(v *string) *TeamADConfigCreate {
	if v != nil {
		_c.SetBaseDn(*v)
	}
	return _c
}

// SetBindDn sets the "bind_dn" field.
func (_c *TeamADConfigCreate) SetBindDn(v string) *TeamADConfigCreate {
	_c.mutation.SetBindDn(v)
	return _c
}

// SetNillableBindDn sets the "bind_dn" field if the given value is not nil.
func (_c *TeamADConfigCreate) SetNillableBindDn(v *string) *TeamADConfigCreate {
	if v != nil {
		_c.SetBindDn(*v)
	}
	return _c
}

// SetBindPasswordCiphertext sets the "bind_password_ciphertext" field.
func (_c *TeamADConfigCreate) SetBindPasswordCiphertext(v string) *TeamADConfigCreate {
	_c.mutation.SetBindPasswordCiphertext(v)
	return _c
}

// SetNillableBindPasswordCiphertext sets the "bind_password_ciphertext" field if the given value is not nil.
func (_c *TeamADConfigCreate) SetNillableBindPasswordCiphertext(v *string) *TeamADConfigCreate {
	if v != nil {
		_c.SetBindPasswordCiphertext(*v)
	}
	return _c
}

// SetCaPem sets the "ca_pem" field.
func (_c *TeamADConfigCreate) SetCaPem(v string) *TeamADConfigCreate {
	_c.mutation.SetCaPem(v)
	return _c
}

// SetNillableCaPem sets the "ca_pem" field if the given value is not nil.
func (_c *TeamADConfigCreate) SetNillableCaPem(v *string) *TeamADConfigCreate {
	if v != nil {
		_c.SetCaPem(*v)
	}
	return _c
}

// SetAllowedGroupDNS sets the "allowed_group_dns" field.
func (_c *TeamADConfigCreate) SetAllowedGroupDNS(v []string) *TeamADConfigCreate {
	_c.mutation.SetAllowedGroupDNS(v)
	return _c
}

// SetRevision sets the "revision" field.
func (_c *TeamADConfigCreate) SetRevision(v int) *TeamADConfigCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *TeamADConfigCreate) SetNillableRevision(v *int) *TeamADConfigCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamADConfigCreate) SetCreatedAt(v time.Time) *TeamADConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamADConfigCreate) SetNillableCreatedAt(v *time.Time) *TeamADConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TeamADConfigCreate) SetUpdatedAt(v time.Time) *TeamADConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TeamADConfigCreate) SetNillableUpdatedAt(v *time.Time) *TeamADConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TeamADConfigCreate) SetID(v uuid.UUID) *TeamADConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamADConfigCreate) SetTeam(v *Team) *TeamADConfigCreate {
	return _c.SetTeamID(v.ID)
}

// Mutation returns the TeamADConfigMutation object of the builder.
func (_c *TeamADConfigCreate) Mutation() *TeamADConfigMutation {
	return _c.mutation
}

// Save creates the TeamADConfig in the database.
func (_c *TeamADConfigCreate) Save(ctx context.Context) (*TeamADConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamADConfigCreate) SaveX(ctx context.Context) *TeamADConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamADConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamADConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamADConfigCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := teamadconfig.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := teamadconfig.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.AllowedGroupDNS(); !ok {
		v := teamadconfig.DefaultAllowedGroupDNS
		_c.mutation.SetAllowedGroupDNS(v)
	}
	if _, ok := _c.mutation.Revision(); !ok {
		v := teamadconfig.DefaultRevision
		_c.mutation.SetRevision(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teamadconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := teamadconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamADConfigCreate) check() error {
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`db: missing required field "TeamADConfig.team_id"`)}
	}
	if _, ok := _c.mutation.DirectoryID(); !ok {
		return &ValidationError{Name: "directory_id", err: errors.New(`db: missing required field "TeamADConfig.directory_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`db: missing required field "TeamADConfig.enabled"`)}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`db: missing required field "TeamADConfig.display_name"`)}
	}
	if _, ok := _c.mutation.AllowedGroupDNS(); !ok {
		return &ValidationError{Name: "allowed_group_dns", err: errors.New(`db: missing required field "TeamADConfig.allowed_group_dns"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`db: missing required field "TeamADConfig.revision"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "TeamADConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "TeamADConfig.updated_at"`)}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`db: missing required edge "TeamADConfig.team"`)}
	}
	return nil
}

func (_c *TeamADConfigCreate) sqlSave(ctx context.Context) (*TeamADConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamADConfigCreate) createSpec() (*TeamADConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamADConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teamadconfig.Table, sqlgraph.NewFieldSpec(teamadconfig.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DirectoryID(); ok {
		_spec.SetField(teamadconfig.FieldDirectoryID, field.TypeUUID, value)
		_node.DirectoryID = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(teamadconfig.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(teamadconfig.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(teamadconfig.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.BaseDn(); ok {
		_spec.SetField(teamadconfig.FieldBaseDn, field.TypeString, value)
		_node.BaseDn = value
	}
	if value, ok := _c.mutation.BindDn(); ok {
		_spec.SetField(teamadconfig.FieldBindDn, field.TypeString, value)
		_node.BindDn = value
	}
	if value, ok := _c.mutation.BindPasswordCiphertext(); ok {
		_spec.SetField(teamadconfig.FieldBindPasswordCiphertext, field.TypeString, value)
		_node.BindPasswordCiphertext = value
	}
	if value, ok := _c.mutation.CaPem(); ok {
		_spec.SetField(teamadconfig.FieldCaPem, field.TypeString, value)
		_node.CaPem = value
	}
	if value, ok := _c.mutation.AllowedGroupDNS(); ok {
		_spec.SetField(teamadconfig.FieldAllowedGroupDNS, field.TypeJSON, value)
		_node.AllowedGroupDNS = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(teamadconfig.FieldRevision, field.TypeInt, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teamadconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(teamadconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamadconfig.TeamTable,
			Columns: []string{teamadconfig.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamADConfig.Create().
//		SetTeamID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamADConfigUpsert) {
//			SetTeamID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamADConfigCreate) OnConflict(opts ...sql.ConflictOption) *TeamADConfigUpsertOne {
	_c.conflict = opts
	return &TeamADConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamADConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamADConfigCreate) OnConflictColumns(columns ...string) *TeamADConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamADConfigUpsertOne{
		create: _c,
	}
}

type (
	// TeamADConfigUpsertOne is the builder for "upsert"-ing
	//  one TeamADConfig node.
	TeamADConfigUpsertOne struct {
		create *TeamADConfigCreate
	}

	// TeamADConfigUpsert is the "OnConflict" setter.
	TeamADConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetTeamID sets the "team_id" field.
func (u *TeamADConfigUpsert) SetTeamID(v uuid.UUID) *TeamADConfigUpsert {
	u.Set(teamadconfig.FieldTeamID, v)
	return u
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamADConfigUpsert) UpdateTeamID() *TeamADConfigUpsert {
	u.SetExcluded(teamadconfig.FieldTeamID)
	return u
}

// SetDirectoryID sets the "directory_id" field.
func (u *TeamADConfigUpsert) SetDirectoryID(v uuid.UUID) *TeamADConfigUpsert {
	u.Set(teamadconfig.FieldDirectoryID, v)
	return u
}

// UpdateDirectoryID sets the "directory_id" field to the value that was provided on create.
func (u *TeamADConfigUpsert) UpdateDirectoryID() *TeamADConfigUpsert {
	u.SetExcluded(teamadconfig.FieldDirectoryID)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *TeamADConfigUpsert) SetEnabled(v bool) *TeamADConfigUpsert {
	u.Set(teamadconfig.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *TeamADConfigUpsert) UpdateEnabled() *TeamADConfigUpsert {
	u.SetExcluded(teamadconfig.FieldEnabled)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *TeamADConfigUpsert) SetDisplayName(v string) *TeamADConfigUpsert {
	u.Set(teamadconfig.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *TeamADConfigUpsert) UpdateDisplayName() *TeamADConfigUpsert {
	u.SetExcluded(teamadconfig.FieldDisplayName)
	return u
}

// SetURL sets the "url" field.
func (u *TeamADConfigUpsert) SetURL(v string) *TeamADConfigUpsert {
	u.Set(teamadconfig.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *TeamADConfigUpsert) UpdateURL() *TeamADConfigUpsert {
	u.SetExcluded(teamadconfig.FieldURL)
	return u
}

// ClearURL clears the value of the "url" field.
func (u *TeamADConfigUpsert) ClearURL() *TeamADConfigUpsert {
	u.SetNull(teamadconfig.FieldURL)
	return u
}

// SetBaseDn sets the "base_dn" field.
func (u *TeamADConfigUpsert) SetBaseDn(v string) *TeamADConfigUpsert {
	u.Set(teamadconfig.FieldBaseDn, v)
	return u
}

// UpdateBaseDn sets the "base_dn" field to the value that was provided on create.
func (u *TeamADConfigUpsert) UpdateBaseDn() *TeamADConfigUpsert {
	u.SetExcluded(teamadconfig.FieldBaseDn)
	return u
}

// ClearBaseDn clears the value of the "base_dn" field.
func (u *TeamADConfigUpsert) ClearBaseDn() *TeamADConfigUpsert {
	u.SetNull(teamadconfig.FieldBaseDn)
	return u
}

// SetBindDn sets the "bind_dn" field.
func (u *TeamADConfigUpsert) SetBindDn(v string) *TeamADConfigUpsert {
	u.Set(teamadconfig.FieldBindDn, v)
	return u
}

// UpdateBindDn sets the "bind_dn" field to the value that was provided on create.
func (u *TeamADConfigUpsert) UpdateBindDn() *TeamADConfigUpsert {
	u.SetExcluded(teamadconfig.FieldBindDn)
	return u
}

// ClearBindDn clears the value of the "bind_dn" field.
func (u *TeamADConfigUpsert) ClearBindDn() *TeamADConfigUpsert {
	u.SetNull(teamadconfig.FieldBindDn)
	return u
}

// SetBindPasswordCiphertext sets the "bind_password_ciphertext" field.
func (u *TeamADConfigUpsert) SetBindPasswordCiphertext(v string) *TeamADConfigUpsert {
	u.Set(teamadconfig.FieldBindPasswordCiphertext, v)
	return u
}

// UpdateBindPasswordCiphertext sets the "bind_password_ciphertext" field to the value that was provided on create.
func (u *TeamADConfigUpsert) UpdateBindPasswordCiphertext() *TeamADConfigUpsert {
	u.SetExcluded(teamadconfig.FieldBindPasswordCiphertext)
	return u
}

// ClearBindPasswordCiphertext clears the value of the "bind_password_ciphertext" field.
func (u *TeamADConfigUpsert) ClearBindPasswordCiphertext() *TeamADConfigUpsert {
	u.SetNull(teamadconfig.FieldBindPasswordCiphertext)
	return u
}

// SetCaPem sets the "ca_pem" field.
func (u *TeamADConfigUpsert) SetCaPem(v string) *TeamADConfigUpsert {
	u.Set(teamadconfig.FieldCaPem, v)
	return u
}

// UpdateCaPem sets the "ca_pem" field to the value that was provided on create.
func (u *TeamADConfigUpsert) UpdateCaPem() *TeamADConfigUpsert {
	u.SetExcluded(teamadconfig.FieldCaPem)
	return u
}

// ClearCaPem clears the value of the "ca_pem" field.
func (u *TeamADConfigUpsert) ClearCaPem() *TeamADConfigUpsert {
	u.SetNull(teamadconfig.FieldCaPem)
	return u
}

// SetAllowedGroupDNS sets the "allowed_group_dns" field.
func (u *TeamADConfigUpsert) SetAllowedGroupDNS(v []string) *TeamADConfigUpsert {
	u.Set(teamadconfig.FieldAllowedGroupDNS, v)
	return u
}

// UpdateAllowedGroupDNS sets the "allowed_group_dns" field to the value that was provided on create.
func (u *TeamADConfigUpsert) UpdateAllowedGroupDNS() *TeamADConfigUpsert {
	u.SetExcluded(teamadconfig.FieldAllowedGroupDNS)
	return u
}

// SetRevision sets the "revision" field.
func (u *TeamADConfigUpsert) SetRevision(v int) *TeamADConfigUpsert {
	u.Set(teamadconfig.FieldRevision, v)
	return u
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *TeamADConfigUpsert) UpdateRevision() *TeamADConfigUpsert {
	u.SetExcluded(teamadconfig.FieldRevision)
	return u
}

// AddRevision adds v to the "revision" field.
func (u *TeamADConfigUpsert) AddRevision(v int) *TeamADConfigUpsert {
	u.Add(teamadconfig.FieldRevision, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *TeamADConfigUpsert) SetCreatedAt(v time.Time) *TeamADConfigUpsert {
	u.Set(teamadconfig.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TeamADConfigUpsert) UpdateCreatedAt() *TeamADConfigUpsert {
	u.SetExcluded(teamadconfig.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamADConfigUpsert) SetUpdatedAt(v time.Time) *TeamADConfigUpsert {
	u.Set(teamadconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamADConfigUpsert) UpdateUpdatedAt() *TeamADConfigUpsert {
	u.SetExcluded(teamadconfig.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TeamADConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(teamadconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TeamADConfigUpsertOne) UpdateNewValues() *TeamADConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(teamadconfig.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamADConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamADConfigUpsertOne) Ignore() *TeamADConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamADConfigUpsertOne) DoNothing() *TeamADConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamADConfigCreate.OnConflict
// documentation for more info.
func (u *TeamADConfigUpsertOne) Update(set func(*TeamADConfigUpsert)) *TeamADConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamADConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamADConfigUpsertOne) SetTeamID(v uuid.UUID) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamADConfigUpsertOne) UpdateTeamID() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateTeamID()
	})
}

// SetDirectoryID sets the "directory_id" field.
func (u *TeamADConfigUpsertOne) SetDirectoryID(v uuid.UUID) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetDirectoryID(v)
	})
}

// UpdateDirectoryID sets the "directory_id" field to the value that was provided on create.
func (u *TeamADConfigUpsertOne) UpdateDirectoryID() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateDirectoryID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *TeamADConfigUpsertOne) SetEnabled(v bool) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *TeamADConfigUpsertOne) UpdateEnabled() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateEnabled()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *TeamADConfigUpsertOne) SetDisplayName(v string) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *TeamADConfigUpsertOne) UpdateDisplayName() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateDisplayName()
	})
}

// SetURL sets the "url" field.
func (u *TeamADConfigUpsertOne) SetURL(v string) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *TeamADConfigUpsertOne) UpdateURL() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateURL()
	})
}

// ClearURL clears the value of the "url" field.
func (u *TeamADConfigUpsertOne) ClearURL() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.ClearURL()
	})
}

// SetBaseDn sets the "base_dn" field.
func (u *TeamADConfigUpsertOne) SetBaseDn(v string) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetBaseDn(v)
	})
}

// UpdateBaseDn sets the "base_dn" field to the value that was provided on create.
func (u *TeamADConfigUpsertOne) UpdateBaseDn() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateBaseDn()
	})
}

// ClearBaseDn clears the value of the "base_dn" field.
func (u *TeamADConfigUpsertOne) ClearBaseDn() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.ClearBaseDn()
	})
}

// SetBindDn sets the "bind_dn" field.
func (u *TeamADConfigUpsertOne) SetBindDn(v string) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetBindDn(v)
	})
}

// UpdateBindDn sets the "bind_dn" field to the value that was provided on create.
func (u *TeamADConfigUpsertOne) UpdateBindDn() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateBindDn()
	})
}

// ClearBindDn clears the value of the "bind_dn" field.
func (u *TeamADConfigUpsertOne) ClearBindDn() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.ClearBindDn()
	})
}

// SetBindPasswordCiphertext sets the "bind_password_ciphertext" field.
func (u *TeamADConfigUpsertOne) SetBindPasswordCiphertext(v string) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetBindPasswordCiphertext(v)
	})
}

// UpdateBindPasswordCiphertext sets the "bind_password_ciphertext" field to the value that was provided on create.
func (u *TeamADConfigUpsertOne) UpdateBindPasswordCiphertext() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateBindPasswordCiphertext()
	})
}

// ClearBindPasswordCiphertext clears the value of the "bind_password_ciphertext" field.
func (u *TeamADConfigUpsertOne) ClearBindPasswordCiphertext() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.ClearBindPasswordCiphertext()
	})
}

// SetCaPem sets the "ca_pem" field.
func (u *TeamADConfigUpsertOne) SetCaPem(v string) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetCaPem(v)
	})
}

// UpdateCaPem sets the "ca_pem" field to the value that was provided on create.
func (u *TeamADConfigUpsertOne) UpdateCaPem() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateCaPem()
	})
}

// ClearCaPem clears the value of the "ca_pem" field.
func (u *TeamADConfigUpsertOne) ClearCaPem() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.ClearCaPem()
	})
}

// SetAllowedGroupDNS sets the "allowed_group_dns" field.
func (u *TeamADConfigUpsertOne) SetAllowedGroupDNS(v []string) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetAllowedGroupDNS(v)
	})
}

// UpdateAllowedGroupDNS sets the "allowed_group_dns" field to the value that was provided on create.
func (u *TeamADConfigUpsertOne) UpdateAllowedGroupDNS() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateAllowedGroupDNS()
	})
}

// SetRevision sets the "revision" field.
func (u *TeamADConfigUpsertOne) SetRevision(v int) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *TeamADConfigUpsertOne) AddRevision(v int) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *TeamADConfigUpsertOne) UpdateRevision() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateRevision()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TeamADConfigUpsertOne) SetCreatedAt(v time.Time) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TeamADConfigUpsertOne) UpdateCreatedAt() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamADConfigUpsertOne) SetUpdatedAt(v time.Time) *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamADConfigUpsertOne) UpdateUpdatedAt() *TeamADConfigUpsertOne {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TeamADConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for TeamADConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamADConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamADConfigUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: TeamADConfigUpsertOne.ID is not supported by MySQL driver. Use TeamADConfigUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamADConfigUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamADConfigCreateBulk is the builder for creating many TeamADConfig entities in bulk.
type TeamADConfigCreateBulk struct {
	config
	err      error
	builders []*TeamADConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamADConfig entities in the database.
func (_c *TeamADConfigCreateBulk) Save(ctx context.Context) ([]*TeamADConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamADConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamADConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamADConfigCreateBulk) SaveX(ctx context.Context) []*TeamADConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamADConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamADConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamADConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamADConfigUpsert) {
//			SetTeamID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamADConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamADConfigUpsertBulk {
	_c.conflict = opts
	return &TeamADConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamADConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamADConfigCreateBulk) OnConflictColumns(columns ...string) *TeamADConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamADConfigUpsertBulk{
		create: _c,
	}
}

// TeamADConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamADConfig nodes.
type TeamADConfigUpsertBulk struct {
	create *TeamADConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamADConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(teamadconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TeamADConfigUpsertBulk) UpdateNewValues() *TeamADConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(teamadconfig.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamADConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamADConfigUpsertBulk) Ignore() *TeamADConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamADConfigUpsertBulk) DoNothing() *TeamADConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamADConfigCreateBulk.OnConflict
// documentation for more info.
func (u *TeamADConfigUpsertBulk) Update(set func(*TeamADConfigUpsert)) *TeamADConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamADConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamADConfigUpsertBulk) SetTeamID(v uuid.UUID) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamADConfigUpsertBulk) UpdateTeamID() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateTeamID()
	})
}

// SetDirectoryID sets the "directory_id" field.
func (u *TeamADConfigUpsertBulk) SetDirectoryID(v uuid.UUID) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetDirectoryID(v)
	})
}

// UpdateDirectoryID sets the "directory_id" field to the value that was provided on create.
func (u *TeamADConfigUpsertBulk) UpdateDirectoryID() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateDirectoryID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *TeamADConfigUpsertBulk) SetEnabled(v bool) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *TeamADConfigUpsertBulk) UpdateEnabled() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateEnabled()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *TeamADConfigUpsertBulk) SetDisplayName(v string) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *TeamADConfigUpsertBulk) UpdateDisplayName() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateDisplayName()
	})
}

// SetURL sets the "url" field.
func (u *TeamADConfigUpsertBulk) SetURL(v string) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *TeamADConfigUpsertBulk) UpdateURL() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateURL()
	})
}

// ClearURL clears the value of the "url" field.
func (u *TeamADConfigUpsertBulk) ClearURL() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.ClearURL()
	})
}

// SetBaseDn sets the "base_dn" field.
func (u *TeamADConfigUpsertBulk) SetBaseDn(v string) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetBaseDn(v)
	})
}

// UpdateBaseDn sets the "base_dn" field to the value that was provided on create.
func (u *TeamADConfigUpsertBulk) UpdateBaseDn() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateBaseDn()
	})
}

// ClearBaseDn clears the value of the "base_dn" field.
func (u *TeamADConfigUpsertBulk) ClearBaseDn() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.ClearBaseDn()
	})
}

// SetBindDn sets the "bind_dn" field.
func (u *TeamADConfigUpsertBulk) SetBindDn(v string) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetBindDn(v)
	})
}

// UpdateBindDn sets the "bind_dn" field to the value that was provided on create.
func (u *TeamADConfigUpsertBulk) UpdateBindDn() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateBindDn()
	})
}

// ClearBindDn clears the value of the "bind_dn" field.
func (u *TeamADConfigUpsertBulk) ClearBindDn() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.ClearBindDn()
	})
}

// SetBindPasswordCiphertext sets the "bind_password_ciphertext" field.
func (u *TeamADConfigUpsertBulk) SetBindPasswordCiphertext(v string) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetBindPasswordCiphertext(v)
	})
}

// UpdateBindPasswordCiphertext sets the "bind_password_ciphertext" field to the value that was provided on create.
func (u *TeamADConfigUpsertBulk) UpdateBindPasswordCiphertext() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateBindPasswordCiphertext()
	})
}

// ClearBindPasswordCiphertext clears the value of the "bind_password_ciphertext" field.
func (u *TeamADConfigUpsertBulk) ClearBindPasswordCiphertext() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.ClearBindPasswordCiphertext()
	})
}

// SetCaPem sets the "ca_pem" field.
func (u *TeamADConfigUpsertBulk) SetCaPem(v string) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetCaPem(v)
	})
}

// UpdateCaPem sets the "ca_pem" field to the value that was provided on create.
func (u *TeamADConfigUpsertBulk) UpdateCaPem() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateCaPem()
	})
}

// ClearCaPem clears the value of the "ca_pem" field.
func (u *TeamADConfigUpsertBulk) ClearCaPem() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.ClearCaPem()
	})
}

// SetAllowedGroupDNS sets the "allowed_group_dns" field.
func (u *TeamADConfigUpsertBulk) SetAllowedGroupDNS(v []string) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetAllowedGroupDNS(v)
	})
}

// UpdateAllowedGroupDNS sets the "allowed_group_dns" field to the value that was provided on create.
func (u *TeamADConfigUpsertBulk) UpdateAllowedGroupDNS() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateAllowedGroupDNS()
	})
}

// SetRevision sets the "revision" field.
func (u *TeamADConfigUpsertBulk) SetRevision(v int) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *TeamADConfigUpsertBulk) AddRevision(v int) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *TeamADConfigUpsertBulk) UpdateRevision() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateRevision()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TeamADConfigUpsertBulk) SetCreatedAt(v time.Time) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TeamADConfigUpsertBulk) UpdateCreatedAt() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamADConfigUpsertBulk) SetUpdatedAt(v time.Time) *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamADConfigUpsertBulk) UpdateUpdatedAt() *TeamADConfigUpsertBulk {
	return u.Update(func(s *TeamADConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TeamADConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the TeamADConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for TeamADConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamADConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
