// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/63747756/jingjiaagent/backend/db/predicate"
	"github.com/63747756/jingjiaagent/backend/db/teamadconfig"
)

// TeamADConfigDelete is the builder for deleting a TeamADConfig entity.
type TeamADConfigDelete struct {
	config
	hooks    []Hook
	mutation *TeamADConfigMutation
}

// Where appends a list predicates to the TeamADConfigDelete builder.
func (_d *TeamADConfigDelete) Where(ps ...predicate.TeamADConfig) *TeamADConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TeamADConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeamADConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TeamADConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(teamadconfig.Table, sqlgraph.NewFieldSpec(teamadconfig.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TeamADConfigDeleteOne is the builder for deleting a single TeamADConfig entity.
type TeamADConfigDeleteOne struct {
	_d *TeamADConfigDelete
}

// Where appends a list predicates to the TeamADConfigDelete builder.
func (_d *TeamADConfigDeleteOne) Where(ps ...predicate.TeamADConfig) *TeamADConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TeamADConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{teamadconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeamADConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
